Repository APPisode-Dev/run-or-not, pull requests merged in 2025-05, with the labels that each got.

#3 merge: Issue Template 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/issue_report.md
Labels: 📚 docs

#10 design/7 : Pretendard Custom Text 추가 및 적용
  assets/fonts/Pretendard-Black.otf
  assets/fonts/Pretendard-Bold.otf
  assets/fonts/Pretendard-ExtraBold.otf
  assets/fonts/Pretendard-ExtraLight.otf
  assets/fonts/Pretendard-Light.otf
  assets/fonts/Pretendard-Medium.otf
  assets/fonts/Pretendard-Regular.otf
  assets/fonts/Pretendard-SemiBold.otf
  assets/fonts/Pretendard-Thin.otf
  lib/design_system/text/custom_text.dart
  lib/design_system/text/pretendard_text.dart
  pubspec.yaml
Labels: 🎨 style

#15 feat/14: 임시 캐릭터 모델 추가
  lib/domain/model/character/custom_character.dart
Labels: ✨ feat
