Repository APPisode-Dev/run-or-not, pull requests merged in 2025-06, with the labels that each got.

#19 feat/18: 캐릭터 이동 로직 개발
  lib/domain/model/character/custom_character.dart
  lib/presentation/game_play/game_play_intent.dart
  lib/presentation/game_play/game_play_state.dart
  lib/presentation/game_play/game_play_view.dart
  lib/presentation/game_play/game_play_view_model.dart
  lib/presentation/router/app_router.dart
Labels: ✨ feat

#23 feat/22: GamePlayViewModel 비즈니스 로직 usecase로 분리
  lib/core/di/injector.dart
  lib/domain/use_case/game/game_use_case.dart
  lib/presentation/game_play/game_play_view_model.dart
Labels: ✨ feat, 🏭 refactor

#30 feat/29: 랭킹 뷰 연결
  lib/core/di/injector.dart
  lib/presentation/game_play/game_play_intent.dart
  lib/presentation/game_play/game_play_state.dart
  lib/presentation/game_play/game_play_view.dart
  lib/presentation/game_play/game_play_view_model.dart
  lib/presentation/ranking/ranking_state.dart
  lib/presentation/ranking/ranking_view_model.dart
  lib/presentation/router/app_router.dart
Labels: ✨ feat

#34 fix/32: TextStyle mabi로 변경 완료
  lib/presentation/game_play/widgets/race_line_list_view.dart
Labels: 🔧 fix

#40 feat/39: Home Detail View 연결 및 base 구조 작업
  lib/core/di/injector.dart
  lib/presentation/home/home_intent.dart
  lib/presentation/home/home_view.dart
  lib/presentation/home/home_view_model.dart
  lib/presentation/home_detail/home_detail_intent.dart
  lib/presentation/home_detail/home_detail_state.dart
  lib/presentation/home_detail/home_detail_view.dart
  lib/presentation/home_detail/home_detail_view_model.dart
  lib/presentation/router/app_router.dart
  lib/presentation/router/app_screen.dart
Labels: ✨ feat

#49 fix/48: Custom Text Style 수정
  lib/design_system/text/custom_text_style.dart
Labels: 🔧 fix

#50 fix: font weight 적용 완료
  lib/design_system/text/custom_text_style.dart
Labels: 🔧 fix

#51 feat/12: Home 1차 개발 완료
  assets/images/horse_blue.png
  assets/images/horse_green.png
  assets/images/horse_red.png
  assets/images/horse_yellow.png
  lib/app/main.dart
  lib/core/di/constant/app_assets.dart
  lib/design_system/color/app_colors.dart
  lib/presentation/home/home_view.dart
  lib/presentation/home/widgets/animated_title_text.dart
  pubspec.yaml
Labels: ✨ feat

#55 feat/24: Setting Base 구조 개발 머지
  lib/core/di/injector.dart
  lib/presentation/home/home_intent.dart
  lib/presentation/home/home_state.dart
  lib/presentation/home/home_view.dart
  lib/presentation/home/home_view_model.dart
  lib/presentation/router/app_router.dart
  lib/presentation/router/app_screen.dart
  lib/presentation/setting/setting_intent.dart
  lib/presentation/setting/setting_state.dart
  lib/presentation/setting/setting_view.dart
  lib/presentation/setting/setting_view_model.dart
Labels: ✨ feat

#59 feat/58: Game Play View 로직 및 UI 개선
  lib/core/di/injector.dart
  lib/domain/model/character/custom_character.dart
  lib/presentation/core/const/app_assets.dart
  lib/presentation/core/widgets/avatar_view.dart
  lib/presentation/game_play/const/game_play_const.dart
  lib/presentation/game_play/game_play_intent.dart
  lib/presentation/game_play/game_play_view.dart
  lib/presentation/game_play/game_play_view_model.dart
  lib/presentation/game_play/utils/random_util.dart
  lib/presentation/game_play/widgets/game_play_button.dart
  lib/presentation/game_play/widgets/race_line_list_view.dart
  lib/presentation/home/home_view.dart
  lib/presentation/home_detail/home_detail_view_model.dart
  lib/presentation/ranking/ranking_view.dart
  lib/presentation/ranking/ranking_view_model.dart
  lib/presentation/ranking/widgets/each_ranking_info_view.dart
  lib/presentation/router/app_router.dart
Labels: ✨ feat, 🎨 style

#63 feat/57: Home Detail View 1차 개발
  lib/presentation/home_detail/home_detail_intent.dart
  lib/presentation/home_detail/home_detail_state.dart
  lib/presentation/home_detail/home_detail_view.dart
  lib/presentation/home_detail/home_detail_view_model.dart
  lib/presentation/home_detail/widgets/character_card.dart
  lib/presentation/home_detail/widgets/character_count_stepper.dart
  lib/presentation/home_detail/widgets/character_name_text_field.dart
  lib/presentation/home_detail/widgets/count_input_text_field.dart
  lib/presentation/home_detail/widgets/start_game_button.dart
  lib/presentation/router/app_router.dart
Labels: ✨ feat

#69 refactor/67: 각 View에 ViewModel 주입(DI)
  lib/presentation/game_play/game_play_view.dart
  lib/presentation/home/home_view.dart
  lib/presentation/home_detail/home_detail_view.dart
  lib/presentation/ranking/ranking_view.dart
  lib/presentation/router/app_router.dart
  lib/presentation/setting/setting_view.dart
Labels: 🏭 refactor

#71 feat/5: rive 작업 완료
  assets/rive_images/horse_blue.riv
  assets/rive_images/horse_green.riv
  assets/rive_images/horse_red.riv
  assets/rive_images/horse_yellow.riv
  lib/app/main.dart
  lib/presentation/game_play/const/rive_setting_const.dart
  lib/presentation/game_play/utils/rive_path_converter.dart
  lib/presentation/game_play/widgets/race_line_list_view.dart
  lib/presentation/game_play/widgets/rive_character.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ feat

#77 feat/75: 설정 버튼 숨기기
  lib/presentation/home/home_view.dart
Labels: ✨ feat

#79 fix/78: ViewModel 싱글톤 이슈 수정
  lib/core/di/injector.dart
  lib/presentation/router/app_router.dart
Labels: 🔧 fix

#83 fix/82: HomeDetail 이전 정보 남아있던 현상 수정
  lib/presentation/home/home_view_model.dart
  lib/presentation/home_detail/home_detail_intent.dart
  lib/presentation/home_detail/home_detail_state.dart
  lib/presentation/home_detail/home_detail_view.dart
  lib/presentation/home_detail/home_detail_view_model.dart
  lib/presentation/router/app_router.dart
  lib/presentation/router/service/router_service.dart
  lib/presentation/router/service/router_service_impl.dart
Labels: 🔧 fix

#85 chore/82: iOS 배포 설정
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/ItunesArtwork@2x.png
  ios/Runner/Info.plist
Labels: ✅ deploy

#86 chore/82: podfile 추가
  ios/Podfile
  ios/Podfile.lock
Labels: ✅ deploy

#88 chore/87: 안드로이드 배포에 필요한 설정 작업
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/ic_launcher-playstore.png
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: ✅ deploy

#90 chore/87: 안드로이드 서명 path 설정, gitignore 설정
  .gitignore
  android/app/build.gradle.kts
Labels: ✅ deploy

#91 development: merge master
  .gitignore
  android/app/build.gradle.kts
Labels: ✅ deploy

#92 chore/87: import 추가
  android/app/build.gradle.kts
Labels: ✅ deploy

#93 development: merge master
  android/app/build.gradle.kts
Labels: ✅ deploy

#94 chore/87: 상대경로 path 수정, 난독화 line 해제
  android/app/build.gradle.kts
Labels: ✅ deploy

#96 chore/87: update targetSdkVersion to 34
  android/app/build.gradle.kts
Labels: ✅ deploy

#97 development: update targetSdkVersion
  android/app/build.gradle.kts
Labels: ✅ deploy

#101 fix/98: 키보드 올라올 때 view도 함께 고려되도록 수정
  lib/presentation/home_detail/home_detail_view.dart
Labels: 🔧 fix

#102 fix/99: 키보드가 올라왔을 때, focus 해제 처리 추가
  lib/presentation/home_detail/home_detail_view.dart
Labels: 🔧 fix

#105 refactor/104: HomeDetail Body 리팩토링(구조 파악을 위해)
  lib/presentation/home_detail/home_detail_view.dart
Labels: 🏭 refactor

#106 development: master merge
  lib/presentation/home_detail/home_detail_view.dart
Labels: 🏭 refactor, 🔧 fix

#108 chore/107: 빌드셋팅
  android/app/build.gradle.kts
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  pubspec.yaml
Labels: ✅ deploy
